import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Headers";
import GlobalContextProvider from "./context/GlobalContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalContextProvider>
            <Header />
            {children}
        </GlobalContextProvider>
      </body>
    </html>
  );
}
